version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    command: python manage.py runserver 0.0.0.0:8005
    ports:
      - "8005:8005"
    networks:
      - schedule-internal-net
      - auth-share-net
    env_file:
      - .env
    depends_on:
      - notification-worker

  notification-worker:
    build: .
    container_name: notification-worker
    command: celery -A notification_service worker --loglevel=info --pool=solo -Q notification_queue
    networks:
      - schedule-internal-net
      - auth-share-net
    env_file:
      - .env

      
networks:
  schedule-internal-net:
    external: true
  auth-share-net:
    external: true
