version: '3.8'

services:
  # PostgreSQL 데이터베이스
  notification-db:
    image: postgres:14
    container_name: notification-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - notification-network

  # RabbitMQ 메시지 브로커
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - notification-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=notification-db
        - DB_PORT=5432
        - SECRET_KEY=${SECRET_KEY}
        - EMAIL_HOST_USER=${EMAIL_HOST_USER}
        - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    container_name: notification-service
    depends_on:
      - notification-db
      - rabbitmq
    networks:
      - notification-network
    restart: always

networks:
  notification-network:
    driver: bridge
volumes:
  notification_db_data: 
